import turtle
alice=turtle.Turtle()
tari=turtle.Turtle()
fishy=turtle.Turtle()
faith=turtle.Turtle()
peter=turtle.Turtle()
bob=turtle.Turtle()
turtle.bgcolor("black")


alice.color("magenta")
tari.color("aqua")
fishy.color("navy")
faith.color("gold")
peter.color("white")
bob.color("coral")

alice.width(10)
tari.width(10)
fishy.width(20)
faith.width(10)
peter.width(10)
bob.width(5)

alice.shape("turtle")
tari.shape("turtle")
fishy.shape("triangle")
faith.shape("turtle")
bob.shape("square")

for times in range(530):
    turtle.tracer(False)
    peter.begin_fill()
    peter.circle(20)
    peter.end_fill()
    alice.stamp()
    tari.stamp()
    fishy.stamp()
    faith.stamp()
    bob.stamp()
    alice.forward(times*3)
    alice.left(120)
    alice.right(200)
    tari.forward(times*3)
    tari.left(115)
    tari.right(200)
    fishy.forward(times*3)
    fishy.left(125)
    fishy.right(200)
    faith.forward(times*3)
    faith.left(130)
    faith.right(200)
    bob.forward(times*3)
    bob.left(110)
    bob.right(200)
    turtle.tracer(True)

    
   
for times in range(200):
    turtle.tracer(False)
    peter.goto(0,0)
    alice.goto(0,0)
    tari.goto(0,0)
    fishy.goto(0,0)
    faith.goto(0,0)
    bob.goto(0,0)
    peter.begin_fill()
    peter.circle(20)
    peter.end_fill()
    alice.forward(times*3)
    alice.left(120)
    alice.right(200)
    tari.forward(times*3)
    tari.left(115)
    tari.right(200)
    fishy.forward(times*3)
    fishy.left(125)
    fishy.right(200)
    faith.forward(times*3)
    faith.left(130)
    faith.right(200)
    bob.forward(times*3)
    bob.left(110)
    bob.right(200)
    turtle.tracer(True)

